// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Touch.Models;

namespace Touch.Models.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20180521104716_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Touch.Models.Folder", b =>
                {
                    b.Property<string>("Path")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Token");

                    b.HasKey("Path");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Touch.Models.Image", b =>
                {
                    b.Property<string>("Path");

                    b.Property<ulong>("Size");

                    b.Property<DateTimeOffset>("DateModified");

                    b.HasKey("Path", "Size", "DateModified");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Touch.Models.Label", b =>
                {
                    b.Property<Guid>("LabelId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("ImageDateModified");

                    b.Property<string>("ImagePath");

                    b.Property<ulong?>("ImageSize");

                    b.Property<int>("Index");

                    b.HasKey("LabelId");

                    b.HasIndex("ImagePath", "ImageSize", "ImageDateModified");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Touch.Models.Label", b =>
                {
                    b.HasOne("Touch.Models.Image")
                        .WithMany("Labels")
                        .HasForeignKey("ImagePath", "ImageSize", "ImageDateModified");
                });
#pragma warning restore 612, 618
        }
    }
}
